/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Products.Clothes;
import Products.Cosmetics;
import Products.Nutrient;
import Products.Product;
import Products.ProductManagement;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmet
 */
public class CPanel extends javax.swing.JFrame {

    private Products.ProductManagement products=new ProductManagement();
    private String companyName ;
    /**
     * Creates new form CPanel
     */
    public CPanel() {
        initComponents();
        UrunEklePanel.setVisible(false);
        UrunSilPaneli.setVisible(false);
    }
    
    public CPanel(String companyName) {
        initComponents();
        this.companyName = companyName;
        UrunEklePanel.setVisible(false);
        UrunSilPaneli.setVisible(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Cikis = new javax.swing.JButton();
        urunEkleButonu = new javax.swing.JButton();
        UrunSilButonu = new javax.swing.JButton();
        UrunuGoster = new javax.swing.JButton();
        UrunEklePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        KategorySecemek = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cinsiyet = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sayisi = new javax.swing.JTextField();
        BedenLabel = new javax.swing.JLabel();
        adi = new javax.swing.JTextField();
        cinsiyetLabel = new javax.swing.JLabel();
        fiyati = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        beden = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        etiket = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        icerik = new javax.swing.JTextField();
        ekle = new javax.swing.JButton();
        UrunSilPaneli = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UrunListesi = new javax.swing.JList<>();
        Sil = new javax.swing.JButton();
        iconLabel = new javax.swing.JLabel();
        bannerText = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1152, 648));
        jPanel1.setMinimumSize(new java.awt.Dimension(1152, 648));
        jPanel1.setPreferredSize(new java.awt.Dimension(1152, 648));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Hoşgeldiniz ......");

        Cikis.setText("Çıkış");
        Cikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CikisActionPerformed(evt);
            }
        });

        urunEkleButonu.setText("Ürün Ekle");
        urunEkleButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkleButonuActionPerformed(evt);
            }
        });

        UrunSilButonu.setText("Ürün Sil");
        UrunSilButonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunSilButonuActionPerformed(evt);
            }
        });

        UrunuGoster.setText("Ürünleri Göster");
        UrunuGoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UrunuGosterActionPerformed(evt);
            }
        });

        jLabel3.setText("Kategori seçiniz:");

        KategorySecemek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giyim", "Kozmetik", "Gıda" }));
        KategorySecemek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategorySecemekActionPerformed(evt);
            }
        });

        jLabel4.setText("Adı:");

        cinsiyet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinsiyetActionPerformed(evt);
            }
        });

        jLabel5.setText("Fiyatı:");

        sayisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sayisiActionPerformed(evt);
            }
        });

        BedenLabel.setText("Bedeni:");

        cinsiyetLabel.setText("Cinsiyet:");

        jLabel8.setText("Etiketleri:");

        jLabel9.setText("İçerikleri:");

        etiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etiketActionPerformed(evt);
            }
        });

        jLabel10.setText("Sayısı:");

        icerik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                icerikActionPerformed(evt);
            }
        });

        ekle.setBackground(new java.awt.Color(204, 204, 255));
        ekle.setText("Ekle");
        ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UrunEklePanelLayout = new javax.swing.GroupLayout(UrunEklePanel);
        UrunEklePanel.setLayout(UrunEklePanelLayout);
        UrunEklePanelLayout.setHorizontalGroup(
            UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UrunEklePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ekle)
                    .addGroup(UrunEklePanelLayout.createSequentialGroup()
                        .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5)
                            .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8)
                                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9)
                                    .addComponent(cinsiyetLabel)
                                    .addComponent(BedenLabel))))
                        .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(KategorySecemek, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiket, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icerik, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(beden, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UrunEklePanelLayout.setVerticalGroup(
            UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UrunEklePanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KategorySecemek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fiyati, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(etiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(icerik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinsiyetLabel)
                    .addComponent(cinsiyet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UrunEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BedenLabel)
                    .addComponent(beden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ekle, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
        );

        UrunListesi.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(UrunListesi);

        Sil.setText("Sil");
        Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UrunSilPaneliLayout = new javax.swing.GroupLayout(UrunSilPaneli);
        UrunSilPaneli.setLayout(UrunSilPaneliLayout);
        UrunSilPaneliLayout.setHorizontalGroup(
            UrunSilPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UrunSilPaneliLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sil)
                .addGap(161, 161, 161))
            .addGroup(UrunSilPaneliLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        UrunSilPaneliLayout.setVerticalGroup(
            UrunSilPaneliLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UrunSilPaneliLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Sil)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UrunEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(UrunSilPaneli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(urunEkleButonu)
                        .addGap(35, 35, 35)
                        .addComponent(UrunSilButonu)
                        .addGap(52, 52, 52)
                        .addComponent(UrunuGoster)
                        .addGap(47, 47, 47)
                        .addComponent(Cikis))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urunEkleButonu)
                    .addComponent(UrunSilButonu)
                    .addComponent(UrunuGoster)
                    .addComponent(Cikis))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UrunEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UrunSilPaneli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        iconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/organic-icon.png"))); // NOI18N
        iconLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        iconLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bannerText.setFont(new java.awt.Font("Tahoma", 3, 48)); // NOI18N
        bannerText.setForeground(new java.awt.Color(0, 153, 0));
        bannerText.setText("ORGANICS");
        bannerText.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("ŞİRKET PANELİ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bannerText, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(357, 357, 357))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bannerText, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(492, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CikisActionPerformed
        Home h = new Home();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_CikisActionPerformed

    private void urunEkleButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkleButonuActionPerformed
        // TODO add your handling code here:
        UrunEklePanel.setVisible(true);
        UrunSilPaneli.setVisible(false);
        
       
        
    }//GEN-LAST:event_urunEkleButonuActionPerformed

    private void UrunSilButonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunSilButonuActionPerformed
        
        DefaultListModel temp=new DefaultListModel();
        
        UrunSilPaneli.setVisible(true);
        Sil.setVisible(true);
        UrunEklePanel.setVisible(false);
        for (int i = 0; i < products.allProducts.size(); i++) {
            temp.addElement(products.allProducts.get(i));
        }
        UrunListesi.setModel(temp);
       
    }//GEN-LAST:event_UrunSilButonuActionPerformed

    private void ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekleActionPerformed
        int kategoryType=-1;
        kategoryType=KategorySecemek.getSelectedIndex();
        System.out.println(kategoryType);
        if(kategoryType==0){
            
           Clothes clothes=new Clothes(adi.getText(), Double.parseDouble(fiyati.getText()), 
                   beden.getText(), cinsiyet.getText(),etiket.getText(), 
                   icerik.getText(), Integer.parseInt(sayisi.getText()));
          products.allProducts.add(clothes);
         
        }
        if(kategoryType==1){
            
           Cosmetics cosmetic=new Cosmetics(adi.getText(), Double.parseDouble(fiyati.getText()),
                    cinsiyet.getText(),etiket.getText(), 
                   icerik.getText(), Integer.parseInt(sayisi.getText()));
          
          
          products.allProducts.add(cosmetic);
          
        }
        if(kategoryType==2){
            
            Nutrient nutr=new Nutrient(adi.getText(), Double.parseDouble(fiyati.getText()),
                    etiket.getText(),icerik.getText(), Integer.parseInt(sayisi.getText()));
           
          products.allProducts.add(nutr);
          
        }
        System.out.println(adi.getText()+ Double.parseDouble(fiyati.getText())+
                    etiket.getText()+icerik.getText()+ Integer.parseInt(sayisi.getText()));
        System.out.println(products.allProducts);
           
        products.writeToCsv();
        
        JOptionPane.showMessageDialog(rootPane,"Ürün başarıyla eklendi");
        UrunEklePanel.setVisible(false);
        
        
    }//GEN-LAST:event_ekleActionPerformed

    private void etiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_etiketActionPerformed

    private void sayisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sayisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sayisiActionPerformed

    private void cinsiyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinsiyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cinsiyetActionPerformed

    private void SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SilActionPerformed
        int index=UrunListesi.getLeadSelectionIndex();
        System.out.print("index "+index);
        products.deleteProduct(index);
        DefaultListModel temp=new DefaultListModel();
        for (int i = 0; i < products.allProducts.size(); i++) {
            temp.addElement(products.allProducts.get(i));
        }
        UrunListesi.setModel(temp);
        
    }//GEN-LAST:event_SilActionPerformed

    private void icerikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_icerikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_icerikActionPerformed

    private void KategorySecemekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategorySecemekActionPerformed
         if(KategorySecemek.getSelectedIndex()==2)
        {
            cinsiyetLabel.setVisible(false);
            cinsiyet.setVisible(false);
            beden.setVisible(false);
            BedenLabel.setVisible(false);
        }
        if(KategorySecemek.getSelectedIndex()==1)
        {
            cinsiyetLabel.setVisible(true);
            cinsiyet.setVisible(true);
            beden.setVisible(false);
            BedenLabel.setVisible(false);
        }
        if(KategorySecemek.getSelectedIndex()==0)
        {
            beden.setVisible(true);
            BedenLabel.setVisible(true);
            cinsiyetLabel.setVisible(true);
            cinsiyet.setVisible(true);
        }
    }//GEN-LAST:event_KategorySecemekActionPerformed

    private void UrunuGosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UrunuGosterActionPerformed
       UrunSilPaneli.setVisible(true);
        UrunListesi.setVisible(true);
       Sil.setVisible(false);
       DefaultListModel temp=new DefaultListModel();
       for (int i = 0; i < products.allProducts.size(); i++) {
            temp.addElement(products.allProducts.get(i));
        }
        UrunListesi.setModel(temp);
       
    }//GEN-LAST:event_UrunuGosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BedenLabel;
    private javax.swing.JButton Cikis;
    private javax.swing.JComboBox<String> KategorySecemek;
    private javax.swing.JButton Sil;
    private javax.swing.JPanel UrunEklePanel;
    private javax.swing.JList<String> UrunListesi;
    private javax.swing.JButton UrunSilButonu;
    private javax.swing.JPanel UrunSilPaneli;
    private javax.swing.JButton UrunuGoster;
    private javax.swing.JTextField adi;
    private javax.swing.JLabel bannerText;
    private javax.swing.JTextField beden;
    private javax.swing.JTextField cinsiyet;
    private javax.swing.JLabel cinsiyetLabel;
    private javax.swing.JButton ekle;
    private javax.swing.JTextField etiket;
    private javax.swing.JTextField fiyati;
    private javax.swing.JTextField icerik;
    private javax.swing.JLabel iconLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField sayisi;
    private javax.swing.JButton urunEkleButonu;
    // End of variables declaration//GEN-END:variables

    private void If(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
